t1=0:0.01:5;
x= (t1.^2).*(t1>=0&t1<=2.5)+(t1.^0.5).*(t1>=2.5&t1<=5);
t2= -fliplr(t1);
y= cos(t2);
h=xcorr(x,y);
a=min(t1)+min(t2);
b=max(t1)+max(t2);
t3=a:0.01:b;
subplot(2,3,1);
plot(t1,x);
xlabel('time');
ylabel('amplitude');
title('i/p Signal');
subplot(2,3,2);
plot(t2,y);
xlabel('time');
ylabel('amplitude');
title('Echo Signal');
subplot(2,3,3);
plot(t3,h);
xlabel('time');
ylabel('amplitude');
title('Cross Correlation');

t1=0:1:4;
x=[1 3 -2 1 2];
t2= -fliplr(t1);
y=[-2 1 4 -1 1.5];
h=xcorr(x,y);
a=min(t1)+min(t2);
b=max(t1)+max(t2);
t3=a:1:b;
subplot(2,3,4);
stem(t1,x);
xlabel('time');
ylabel('amplitude');
title('i/p Sequence');
subplot(2,3,5);
stem(t2,y);
xlabel('time');
ylabel('amplitude');
title('Echo Sequence');
subplot(2,3,6);
stem(t3,h);
xlabel('time');
ylabel('amplitude');
title('Cross Correlation');
